# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import worker.models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_description', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to=worker.models.get_upload_file_name)),
                ('posted_on', models.DateTimeField(verbose_name='Date Posted')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.Worker')),
            ],
        ),
    ]
