# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
