# Generated by Django 2.0.5 on 2018-05-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='likes_this_site',
            field=models.BooleanField(default=True),
        ),
    ]
